### ISSUE TITLE
Slashes within the journal id.

### ISSUE THREAD

**Issue by engelir** [clarivate/wosjournals-java-client#4]
How can the slash within the journal id be handled? Without handling the request does not work.

Example: 
"INT_J_PRESS/POLIT"
JournalRecord result = apiInstance.journalsIdGet("INT_J_PRESS/POLIT"); -> Bad request!

**Comment by maloku** [comment]
@engelir, thank you for reporting the issue. I have fixed it. Please pull the recent changes to get the fix.

**Comment by engelir** [comment]
@maloku: Thank you!  One of two functions I use still doesn't work.

Works:			JournalRecord journalRecord =  journalsApi.journalsIdGet(id);
**Doesn't work**:	JournalReports journalReports = journalsApi.journalsIdReportsYearYearGet( id, jcrYear);
